### ISSUE TITLE
Change <services> tag to <extensions> or <plugins>

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-configuration#27]
Services are not descriptive of what the server plugins are actually doing.  Change the tag to either <extensions> or <plugins>

**Comment by myronkscott** [comment]
@ljacomet @GaryWKeim  please provide feedback asap as to which you prefer.  I would like to make this change immediately.  Also this will break every config so maybe we should consider not changing it but I think it is a good change.

**Comment by myronkscott** [comment]
Plugins is nice because is provides association will the directory that contains all the plugin jars

**Comment by myronkscott** [comment]
Another possibility is versioning the schema and trying to support both.

**Comment by ljacomet** [comment]
@myronkscott Ok with plugin, I would not try to version nor support both, that's why we released stuff in beta only so far.

**Comment by GaryWKeim** [comment]
Good w/plugins.
