### ISSUE TITLE
<entity> element should be unique

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/terracotta-configuration#45]
Currently duplicated <entity> elements are not validated and cluster is successfully booted. It better be unique to catch duplicated entities during cluster is booted.

**Comment by myronkscott** [comment]
We de-duplicate by type and name in the configuration at processing time.  Items later in the configuration take precedence over earlier items.  Entities defined in the configuration take precedence over annotation defined permanent entities.  We will properly document this.
