### ISSUE TITLE
Improve XSD to differentiate types accepted in plugins

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-configuration#48]
Currently the XSD does not limit the types that can be present under `plugins/config` or `plugins/service` which means that when using a tool allowing to autocomplete XML, extensions for either section are proposed into both sections.

However, at runtime the types have very different behaviour and will fail if used out of place.

We should improve the XSD to request specific type extensions in either position thus allowing better tool support when writing config files.

**Comment by ljacomet** [comment]
Ideally this gets fixed both in 10.2.x and master as it would be a compatible change.

**Comment by myronkscott** [comment]
I'm not sure I fully understand the problem here.  Are you saying that 
```
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:choice>
        <xs:element name="config" type="tc:service"/>
        <xs:element name="service" type="tc:service"/>
      </xs:choice>
    </xs:sequence>
```
should be 

```
    <xs:sequence>
        <xs:element name="config" type="tc:service" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="service" type="tc:service" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
```

???

**Comment by ljacomet** [comment]
No, I was thinking of something akin to what we do in Ehcache:

```xml
  <xs:complexType name="resources-type">
    <xs:sequence>
      <xs:element ref="ehcache:resource" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="resource" abstract="true">
    <xs:annotation>
      <xs:appinfo>
        <jaxb:dom/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>

  <xs:element name="heap" type="ehcache:resource-type" substitutionGroup="ehcache:resource">
    <xs:annotation>
      <xs:appinfo>
        <jaxb:class/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
```
where a type is defined to contain a ref to an abstract one and you then have concrete implementation of that type in either `config` or `service` extensions. And they would be two different types so that there is no valid use of either in the other.
